<a href="https://colab.research.google.com/github/Basurero2/Visualizacion-de-Datos-estilizando-tablas-con-Python/blob/juan-carlos/Estilizacion_de_tablas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Visualization: Estilizando tablas con python**

## **Extracción y preparación de los datos**

In [148]:
#!pip install pandas==2.0.0
#esto es para instalar pandas en otro entorno, la version varia asi que revisa la documentacion
#para ver en que version esta actualmente

In [149]:
import pandas as pd

print(pd.__version__)   #version de pendas que tenemos instalado en este entorno

2.2.2

In [150]:
url = "https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv"
#tambien puedes usar el csv que esta en carpeta de base de datos en el repositorio

#url = "informe de ventas.csv"

In [151]:
#pd.read_csv('informe de ventas.csv',
 #                sep='#',
 #               engine="python",               # El motor 'python' maneja mejor el quoting=3
 #               quoting=3,                     #ignora comillas que pueden romper estructura (clave)
 #               on_bad_lines='warn')           #da un mensaje alerta si falla
#el archivo tiene en cada fila " ", producto de un convertir de txt a csv

In [152]:
#ventas.columns

intente convertir desde paginas un archivo txt en csv, pero me daban errores (lineas codigo arriba), asi que lo voy a convertir desde aqui con pandas

In [153]:
archivo = pd.read_csv('ventas.txt', sep="#")
archivo.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [154]:
archivo.to_csv("informe de ventas.csv", sep=",", index=False)

In [155]:
ventas = pd.read_csv("informe de ventas.csv")
ventas.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [156]:
ventas = ventas[['fecha_pedido',
 'modo_envio',
 'nombre_cliente',
 'segmento_cliente',
 'ciudad',
 'provincia',
 'region',
 'departamento',
 'tipo_producto',
 'cantidad',
 'ventas',
 'ganancia']]

In [157]:
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,cantidad,ventas,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,2,890.66,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,3,2488.59,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,2,49.72,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,5,3255.75,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,2,76.04,4.28

In [158]:
ventas.shape

(8940, 12)

In [159]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   cantidad          8940 non-null   int64
 10  ventas            8940 non-null   float64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

In [160]:
ventas["fecha_pedido"] = pd.to_datetime(ventas["fecha_pedido"], format="%Y-%m-%d")

In [161]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   cantidad          8940 non-null   int64
 10  ventas            8940 non-null   float64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

## Misión 1: Equipo de Ventas

Necesitamos construir una visualización para indicar los **10 principales clientes por total de ventas**.

Con ello, el equipo de ventas puede pensar en estrategias para mantener a estos clientes comprando en nuestra tienda.

In [162]:
ventas.nlargest(10, columns="ventas")

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,cantidad,ventas,ganancia
6100,2018-10-03,Entrega estándar,Víctor Carrasco,B2B,Quilmes,Buenos Aires,Buenos Aires,Automotriz,Piezas de repuesto,5,59499.85,14280.00
7314,2019-03-24,Envío rápido,Laura Rojas,B2C,San Miguel de Tucumán,Tucumán,Norte,Automotriz,Piezas de repuesto,4,47599.84,11423.92
2369,2019-10-23,Envío rápido,Brisa Rojas,B2B,La Plata,Buenos Aires,Buenos Aires,Automotriz,Piezas de repuesto,4,38079.88,6663.96
3748,2019-11-18,Entrega estándar,Alejandro Sánchez,B2C,Mar del Plata,Buenos Aires,Buenos Aires,Automotriz,Piezas de repuesto,3,35699.91,8568.00
8085,2018-12-18,Entrega estándar,Cristina Barrios,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,13,33635.29,8408.79
3659,2016-09-24,Entrega estándar,Mateo Vargas,B2C,Tartagal,Salta,Norte,Jardinería y paisajismo,Herramientas de jardinería,5,32129.85,7871.85
3817,2018-04-17,Entrega estándar,Germán Cervantes,B2B,Orán,Salta,Norte,Automotriz,Equipos de limpieza,7,30939.79,4022.20
7597,2018-02-03,Económica,Montserrat Paredes,B2C,Posadas,Misiones,Litoral,Automotriz,Equipos de limpieza,5,29749.85,4760.00
5730,2018-05-24,Entrega estándar,Carlos Sánchez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Automotriz,Piezas de repuesto,4,28559.92,1904.00
2265,2016-07-26,Económica,Lucía Díaz,B2C,Mendoza,Mendoza,Cuyo,Jardinería y paisajismo,Materiales de paisajismo,5,27838.00,556.75

In [163]:
clientes = ventas.groupby("nombre_cliente")["ventas"].sum().nlargest(10).copy()
clientes

#nlargest : ordena de mayor a menor, segun una columna(s), por defecto muestra 5 filas
#copy() : genera una copia del DataFrame original y hacer esa operacion, se recomienda hacer en filtro o slice

nombre_cliente
Víctor Carrasco      73370.61
Brisa Rojas          68868.11
Mateo Vargas         62749.75
Vicente Rojas        59544.11
Laura Rojas          51398.87
Lucía Díaz           48178.99
Cristina Barrios     47610.80
Alejandro Sánchez    43769.25
Pamela Huerta        42354.19
Carlos Sánchez       41238.81
Name: ventas, dtype: float64

In [164]:
clientes = clientes.reset_index()
clientes

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [165]:
clientes.index

RangeIndex(start=0, stop=10, step=1)

In [166]:
# dic = {"nombre_cliente":"Clientes", "ventas":"Ventas"}
# clientes = clientes.rename(columns=dic)
# esto es si quieres cambiar columnas pero solo especificando cuales, y no poniendo todo en secuencia como abajo

clientes.columns = ["Clientes", "Ventas"]  #cambiamos los nombres de las columnas, es por orden (todas columnas)
clientes["Ranking"] = clientes.index + 1   #creamos una columna con los valores del index predetemrinado
clientes = clientes.set_index("Ranking")   #convertir en un indice la columna "Ranking"
clientes

                  Clientes    Ventas
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

Objeto style

In [167]:
estilo = clientes.style   #creamos un objeto tipo style apartir de un DataFrame, para usar sus metodos
estilo                    # y estilizar la tabla que guardamos en una variable estilo

In [168]:
estilo.format({"Ventas":"{:,.2f}"}) #aplicamos un modificacion de visualizacion a los valores de Vnetas
estilo                              #aplique "," para separa miles y "." para los decimales con 2 decimales (2f)
                                    #ya lo aplica directamente

In [169]:
estilo

## Desafío

En él, tenemos un informe de costos de venta de libros y películas de una tienda. Durante los desafíos, la misión será trabajar con los datos para crear tablas que se adapten a las necesidades de diversos análisis que pueden realizarse en la tienda. Para una mejor comprensión de los datos, a continuación se muestra lo que representa cada dato en las columnas.

- pais: país de destino del producto.
- id_cliente: código de identificación del cliente solicitante.
- fecha_pedido: fecha de solicitud del producto por parte del cliente.
- fecha_llegada: fecha de llegada del producto a la dirección de entrega proporcionada por el cliente.
- tipo_compra: categoría a la que pertenece la compra, que puede ser Normal o Devolución.
- numero_pedido: código de identificación de la compra realizada.
- tamano_pacote: tamaño del paquete para el envío del pedido.
- unidades: cantidad de unidades compradas en el pedido.
- costo_empacado: valor del costo de empaquetado del producto para la tienda.
- costo_envio: valor del costo de envío del producto para la tienda.
- tipo_descuento: categoría del tipo de descuento aplicado.
- categoria: categoría del tipo de producto.
- tipo_consumo: nivel de consumo del producto por tiempo de uso.
- tipo_cliente: categoría del tipo de cliente.
- costo_producto: valor total del costo que resulta el pedido para la tienda.

El primer desafío es construir una visualización que permita identificar qué países han solicitado más productos por pedidos, para así poder realizar un estudio sobre la distribución y logística de productos.

In [170]:
#enlace csv : "https://gist.githubusercontent.com/ahcamachod/52da15c2bbb31e4270b5c267dd051473/raw/62c366878ebd4be2ec899836413c8d1f3e116c01/tienda_libros.csv")

In [171]:
ar = pd.read_csv("https://gist.githubusercontent.com/ahcamachod/52da15c2bbb31e4270b5c267dd051473/raw/62c366878ebd4be2ec899836413c8d1f3e116c01/tienda_libros.csv")

In [172]:
ar.to_csv("d1_tienda_libros.csv", index=False)

In [173]:
tienda_libros = pd.read_csv("d1_tienda_libros.csv")
tienda_libros.head()

,pais,id_cliente,fecha_pedido,fecha_llegada,tipo_compra,numero_pedido,tamano_paquete,unidades,costo_empacado,costo_envio,tipo_descuento,categoria,tipo_consumo,tipo_cliente,costo_producto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Paquete pequeño,1,3.0,5.99,Sin descuento,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Paquete pequeño,3,1.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Paquete pequeño,1,3.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolución,98077986,Paquete pequeño,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Paquete pequeño,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [174]:
df_paises = tienda_libros.groupby("pais")["unidades"].sum().nlargest(9).reset_index().copy()
df_paises

        pais  unidades
0  Argentina      5591
1    Ecuador      5566
2   Paraguay      5564
3       Perú      5550
4  Venezuela      5529
5   Colombia      5504
6     Brasil      5473
7    Uruguay      5377
8      Chile      5304

In [175]:

df_paises.columns = ["Paises", "Unidades pedidas/transportadas"]     #cambio nombre columnas
df_paises["Ranking"] = df_paises.index + 1           #crea columna para ranking
df_paises = df_paises.set_index("Ranking")           #convertir en index la columna ranking
df_paises

            Paises  Unidades pedidas/transportadas
Ranking
1        Argentina                            5591
2          Ecuador                            5566
3         Paraguay                            5564
4             Perú                            5550
5        Venezuela                            5529
6         Colombia                            5504
7           Brasil                            5473
8          Uruguay                            5377
9            Chile                            5304

In [176]:
s_pais = df_paises.style                                         #guardamos el DF como objeto style
s_pais.format({"Unidades pedidas/transportadas": "{} prod"})     #añadimos "prod" en esa clumna
s_pais

# Misión 2: Equipo Comercial

Necesitamos construir una visualización que permita asociar el **total de ganancias en ventas y el total de lucros por tipo de producto**.

Ello permitirá que el equipo comercial pueda enfocarse en estrategias para apalancar los ingresos que se reciben con cada tipo de producto vendido en la tienda.

In [177]:
ganancias_ventas = ventas.groupby("tipo_producto")[["ventas", "ganancia"]].sum()
ganancias_ventas

                                 ventas  ganancia
tipo_producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [178]:
ganancias_ventas.index.name

'tipo_producto'

In [179]:
ganancias_ventas.index.name = "tipo de producto"

In [180]:
s_producto = ganancias_ventas.style   #creamos una mascara de estilo, nos muestre tabla en crudo
s_producto

In [181]:
s_producto.format("USD {:,.2f}").highlight_max(color="lightgreen").highlight_min(color="red")
#aplicamos formato de numero a todos las columnas (numerica)
#aplicamos un resaltado a los valores min de cada columna : rojo
#aplicamos un resaltado a los valores maximos de cada columa : verde claro

In [182]:
s_producto.background_gradient(cmap="Greens") #aplicamos una gradiente de color verde
                                              #le color max oscuro es el mayor, y mas claro es menor valor

In [183]:
encabezado = {
    "selector" : "th",
    "props" : "text-align:center; font-family:Arial; font-weight:bold; text-transform:capitalize"
}
#dict con "selector" : th, td, especificar a que se le hara el estilo
#props : son las propiedades de css

s_producto.set_table_styles([encabezado], overwrite=False)
#aplica estilo a la estructura a nivel tabla
#overwrite False : añade estilo (mantiene el estil oanterior, solo agrega mas estilos)
#overwrite True : reemplaza estilo anteriores, si son mismo selector (diferentes puede solo añada)

## Desafio

Aprendimos a construir una visualización capaz de resaltar elementos a través de algunas funciones integradas. Y, en este desafío, podemos aplicar algunas de esas funciones.

El objetivo de este desafío es construir una visualización que permita identificar qué categorías de productos generaron más y menos costos para la tienda.

Recuerda que, para continuar con el desafío, necesitas usar el fechaset [tienda_libros.csv](https://gist.githubusercontent.com/ahcamachod/52da15c2bbb31e4270b5c267dd051473/raw/62c366878ebd4be2ec899836413c8d1f3e116c01/tienda_libros.csv). El diccionario de datos que describe este conjunto está disponible en el desafío de la clase 1.

In [184]:
tienda_libros.head()

,pais,id_cliente,fecha_pedido,fecha_llegada,tipo_compra,numero_pedido,tamano_paquete,unidades,costo_empacado,costo_envio,tipo_descuento,categoria,tipo_consumo,tipo_cliente,costo_producto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Paquete pequeño,1,3.0,5.99,Sin descuento,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Paquete pequeño,3,1.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Paquete pequeño,1,3.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolución,98077986,Paquete pequeño,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Paquete pequeño,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [185]:
categorias = tienda_libros.groupby("categoria")["costo_producto"].sum().copy()
categorias = categorias.reset_index()
categorias.columns = ["Categoria producto", "Costo de pedidos"]
categorias = categorias.set_index("Categoria producto")
#categorias.index.name = "Categoria producto"
#categorias.column = ["Costo de pedidos"]

In [186]:
s_categorias = categorias.style                #creamos una mascara de estilo
s_categorias.format("PEN {:,.2f}").highlight_max(color="lightgreen").highlight_min(color="red")

# Misión 3: Equipo de Logística

Necesitamos construir una visualización que nos permita entender la **distribución de pedidos por región de Brasil**.

Así, el equipo de logística va a saber dónde hay más oportunidad de enfocar los esfuerzos de material y mano de obra.

In [187]:
ventas.head()

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,cantidad,ventas,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,2,890.66,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,3,2488.59,373.29
2,2018-06-13,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,2,49.72,11.68
3,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,5,3255.75,-651.15
4,2017-10-12,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,2,76.04,4.28

In [188]:
region = pd.DataFrame(ventas["region"].value_counts())  #convertimos en un DataFrame esa serie
                                                        #donde mmuestra la cantidad de registros agrupados
region.columns = ["Nº Pedidos"]
region.index.name = "Region"
region

              Nº Pedidos
Region
Buenos Aires        2822
Litoral             1924
Norte               1555
Central             1276
Cuyo                 915
Patagónica           448

Vamos a agrega runa columna de porcentaje de cada valor sobre el total, para ello utilizaremos numpy

In [189]:
import numpy as np
#para realizar operaciones en un array con varias datos, mas optimo

In [190]:
porcentaje = region["Nº Pedidos"].to_numpy()   #convertimos en un numpy array esa serie
porcentaje = 100*porcentaje/porcentaje.sum()      #aplicamos formula porcentaje a todos valores del array
porcentaje

array([31.56599553, 21.5212528 , 17.39373602, 14.27293065, 10.23489933,
        5.01118568])

In [191]:
region["Porcentaje de Pedidos"] = porcentaje                #creamos una columna con los valores del array que operamos
region

              Nº Pedidos  Porcentaje de Pedidos
Region
Buenos Aires        2822              31.565996
Litoral             1924              21.521253
Norte               1555              17.393736
Central             1276              14.272931
Cuyo                 915              10.234899
Patagónica           448               5.011186

Vamos a estilizarlo para que se vea mejor

In [192]:
s_region = region.style
s_region

In [193]:
encabezado = {
    "selector": "th",
    "props": "font-family:Arial; font-weight:bold; text-align:right; background-color:white; color:black"
}
# th : afecta a las encabezados y al indice como a sus valores del indice

celdas = {
    "selector": "td",
    "props": "text-align:right; background-color:white; color:black"
}
#td : afecta a los valores de las columnas, contenido

s_region.set_table_styles([encabezado, celdas])

In [194]:
s_region.format({"Porcentaje de Pedidos": "{:.2f} %"})\
                  .bar(subset="Porcentaje de Pedidos", vmin=0, vmax=100, color="#9cd3bb")

Otras funciones built-in
- highlight_null : resaltar valores nulos
- highlight_between : resaltar valores en un rango
- highlight_quantile : resaltar rango de cuantil especifico
- text_gradient : es como background_gradiente pero para el texto

Ejemplo con los dos primeros

In [195]:
import pandas as pd
import numpy as np

datos = pd.DataFrame({'ID': [1204, 3018, 9963, 1005, 5627],
                   'Edad': [np.nan, 32, 19, np.nan, 38],
                   'Salario': [3500.00, 4200.50, 2800.00, 5700.25, 4900.75]})

In [196]:
s_datos = datos.style.format({"Edad": "{:.0f}", "Salario": "PEN {:,.2f}"}).highlight_null(color="#F79747")
s_datos

In [197]:
s_datos.highlight_between(left=4000, right=5000, axis=1, color='#94B2D7')
#se aplico limites directos (numeros), la cual afecta a todos los valores de la columnas (axis 1)

In [198]:
s_datos.highlight_between(subset="Salario",left=4000, right=5000, axis=1, color='#94B2D7')
#aplica solo a la columna (axis 1) Salario

In [199]:
limite_inferior = pd.Series([4000.0], index=['Salario'])    # 1 forma de crear una serie, es para indicar en que columna se realizara
limite_inferior = pd.Series({"Salario" : 4000, "Edad":0})   # 1 forma tambien de crear una serie,

limite_superior = pd.Series({"Salario": 5000, "Edad":20})   #especificar el limite para cada columna
                                                            #se puede poner una lista simple con numeros en secuencia, pero es mas elegante asi

In [200]:
s_datos.highlight_between(left=limite_inferior, right=limite_superior, axis=1, color='#94B2D7')
#se aplica una serie como limites, que indican en que columna se haran, pero se aplica un solo color

Si quieres aplicar varios filtros  pero con diferentes colores, aplicamos una secuencia de funciones

In [201]:
s_datos.highlight_between(subset="Edad",left=0, right=20, color="lightblue").highlight_between(subset="Salario", left=4000, right=5000, color="lightgreen")

Si quieres aplicar varios filtros con highlight_between y con diferentes colores, aplicamos un diccionario con los parametros, para que sea mas ordenado

In [202]:
reglas = {
    'Edad': {'left': 0, 'right': 20, 'color': 'lightblue'},
    'Salario': {'left': 4000, 'right': 5000, 'color': 'lightgreen'}
}

# Aplicamos todo dinámicamente
for col, params in reglas.items():
    s_datos.highlight_between(subset=col, **params)

s_datos

## Desafio

El desafío consiste en construir una visualización que permita informar la cantidad y distribución de pedidos por tipo de descuento. Esto permitirá que los departamentos de la empresa comprendan la demanda de productos en cada promoción.

Recuerda que, para continuar con el desafío, debes trabajar con el conjunto de datos tienda_libros.csv

In [203]:
tienda_libros.head()

,pais,id_cliente,fecha_pedido,fecha_llegada,tipo_compra,numero_pedido,tamano_paquete,unidades,costo_empacado,costo_envio,tipo_descuento,categoria,tipo_consumo,tipo_cliente,costo_producto
0,Argentina,111962928,2002-02-15,2002-03-10,Normal,98091426,Paquete pequeño,1,3.0,5.99,Sin descuento,BlueRay,Alto Consumo,B2C,8.99
1,Argentina,145148150,2004-11-05,2004-11-26,Normal,98087803,Paquete pequeño,3,1.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,7.99
2,Argentina,194622983,2014-09-14,2014-09-28,Normal,98072296,Paquete pequeño,1,3.0,6.99,Sin descuento,BlueRay,Alto Consumo,B2C,9.99
3,Argentina,220834258,2011-07-20,2011-07-30,Devolución,98077986,Paquete pequeño,2,1.0,3.86,Cyber Monday,BlueRay,Alto Consumo,B2B,4.86
4,Argentina,220834258,2013-09-15,2017-02-15,Normal,98074234,Paquete pequeño,1,2.0,4.88,Black Friday,BlueRay,Alto Consumo,B2B,6.88

In [204]:
df_descuentos = tienda_libros["tipo_descuento"].value_counts().to_frame()
df_descuentos
#convertimos a DataFrame

                count
tipo_descuento
Sin descuento   13347
Cyber Monday     6922
Black Friday     1986
Liquidación      1487
Fecha especial   1148

In [205]:
df_descuentos.index.name = "Tipo de descuento"
df_descuentos.columns = ["Cantidad de pedidos"]
df_descuentos
#Cambiamos los nombes del index y columna

                   Cantidad de pedidos
Tipo de descuento
Sin descuento                    13347
Cyber Monday                      6922
Black Friday                      1986
Liquidación                       1487
Fecha especial                    1148

In [206]:
import numpy as np

In [207]:
porcentaje = df_descuentos["Cantidad de pedidos"].to_numpy()
porcentaje = 100*porcentaje/porcentaje.sum()
porcentaje
#creamos un numpy array donde estaran los porcentajes para valores de nueva columna

array([53.62394536, 27.81036561,  7.97910808,  5.97428686,  4.61229409])

In [209]:
df_descuentos["Porcentaje de pedidos"] = porcentaje
df_descuentos
#creamos una nueva columna con los valores de porcetaje (numpy array)

                   Cantidad de pedidos  Porcentaje de pedidos
Tipo de descuento
Sin descuento                    13347              53.623945
Cyber Monday                      6922              27.810366
Black Friday                      1986               7.979108
Liquidación                       1487               5.974287
Fecha especial                    1148               4.612294

In [210]:
s_descuentos = df_descuentos.style
s_descuentos.format({"Porcentaje de pedidos": "{:.2f} %"})\
                  .bar(subset="Porcentaje de pedidos",vmin=0, vmax=100, color="#093364", axis=1,
                       width=60, height=50)
#creamos una mascara de estilos a nuestro DataFrame
#aplicamos un formato a los valores de porcentaje
#agregas un grafico de barras a la columna porcentajes, aplicamos color, limites referencia
#ancho y altura

Resultado final

In [212]:
encabezados = {
    "selector": "th",
    "props": "font-family:Arial; font-weight:bold; text-align:right; background-color:white; color:black"
}

celdas = {
    "selector" : "td",
    "props" : "text-align:right; background-color:white; color:black"
}

s_descuentos.set_table_styles([encabezados, celdas])
#aplicamos un propiedas css para la tabla completa, para encabezados y celdas (valores columnas)
#resultado final

# Misión 4: Equipo de Logística

Nuevamente el equipo de logística desea replantear su estructura y organización de provisionamiento de productos e, para ello, se pensó en una visualización que permita identificar el estándar de la **cantidad de productos solicitados por mes por departamento**.

# Misión 5: Informe de Desempeño

El informe de desempeño es un documento muy importante para la empresa. En este, todos los que trabajan en la tienda pueden entender cómo está la empresa. Debido a ello, las tablas bien construídas son esenciales para mostrar los datos de la mejor forma.

Por lo tanto, necesitamos construir una visualización que permita entender la **relación entre tipos de clientes y modo de envío de productos de acuerdo con las ventas**. De esta forma, será posible destacar en el informe cuál es el modo de envío y cuáles son los que más generaron lucro en las ventas.